### ISSUE TITLE
Wildfly Deployment context-root parameter problem

### ISSUE THREAD

**Issue by mehmetkasalak** [OctopusDeploy/Octopus.Dependencies.Java#3]
Hi,

I want to deploy wildfly with domain (server group) via Octopus but I also want to give context-root from the Octopus step. But there is only one option for deployment name and there isn't any parameter available for runtime-name which is used for creating context via cli.

Is there any way to do it? Or any suggestions?

Ps. : aloha is an example deployment name, but I don't see any parameter for runtime-name

![image](https://user-images.githubusercontent.com/4425298/85418729-cfc9ca80-b579-11ea-843a-4ad7cda47359.png)

**Comment by mcasperson** [comment]
The context path for a WildFly deployment by default matches the name of the application package. For example, deploying myapp.war results in a context path of myapp. 

From your screenshot the deployment name is missing the ".war" extension. Setting the deployment name to simply "aloha" will successfully upload the file to WildFly, but WildFly will not deploy it as it does not recognize the package.

Alternatively the context path can be defined in the jboss-web.xml file, which is described at https://docs.jboss.org/jbossas/guides/webguide/r2/en/html/ch06.html.
